//
// Created by levy on 2019/3/17.
//

#ifndef FLYSENTINEL_SHAREDOBJECTDEF_H
#define FLYSENTINEL_SHAREDOBJECTDEF_H

const int OBJ_SHARED_BULKHDR_LEN = 32;
const int PROTO_SHARED_SELECT_CMDS = 10;

#endif //FLYSENTINEL_SHAREDOBJECTDEF_H
