//
// Created by levy on 2019/5/5.
//

#ifndef FLYSENTINEL_ABSTRACTINSTANCELINK_H
#define FLYSENTINEL_ABSTRACTINSTANCELINK_H

class AbstractInstanceLink {

};

#endif //FLYSENTINEL_ABSTRACTINSTANCELINK_H
