//
// Created by levy on 2019/5/27.
//

#ifndef FLYSENTINEL_SCRIPTJOBDEF_H
#define FLYSENTINEL_SCRIPTJOBDEF_H

const int SENTINEL_SCRIPT_NONE = 0;
const int SENTINEL_SCRIPT_RUNNING = 1;

#endif //FLYSENTINEL_SCRIPTJOBDEF_H
